apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

namespace: hello-app

images:
  - name: hello-app
    newName: diegomattozo/argo-cd-playground
    newTag: test
